export const FACTS: string[] = [
  "Your brain generates about 23 watts of power — enough to light a small LED bulb.",
  "Octopuses have three hearts, two of which stop beating when they swim.",
  "A group of flamingos is called a flamboyance. Nobody is surprised.",
  "Humans share 50% of their DNA with bananas. So technically, a banana is your distant cousin.",
  "The average person walks about 100,000 miles in their lifetime — roughly four times around the Earth.",
  "Cows have best friends and get stressed when separated from them.",
  "The inventor of the Pringles can is buried in one.",
  "A day on Venus is longer than a year on Venus.",
  "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.",
  "Wombat poop is cube-shaped. Scientists spent years figuring out why.",
  "Your brain is more active at night than during the day.",
  "A snail can sleep for three years straight.",
  "The word 'nerd' was first used by Dr. Seuss in 1950.",
  "Banging your head against a wall burns 150 calories per hour. Please don't.",
  "Honey never expires — archaeologists found 3000-year-old honey in Egyptian tombs and it was still edible.",
  "A group of crows is called a murder. A group of cats is called a clowder. English is wild.",
  "The brain itself feels no pain — it has no pain receptors.",
  "There are more possible games of chess than atoms in the observable universe.",
  "Butterflies taste with their feet.",
  "The Eiffel Tower grows about 15cm taller in summer due to heat expanding the metal.",
  "A human brain has enough storage capacity to hold 2.5 million gigabytes of data.",
  "Sharks are older than trees — they existed 400 million years ago.",
  "The unicorn is the national animal of Scotland.",
  "It is impossible to hum while holding your nose closed. You just tried it.",
  "Penguins propose to their mates with a pebble.",
  "An ostrich's eye is bigger than its brain.",
  "The average person spends 6 months of their lifetime waiting for red lights to turn green.",
  "A goldfish has a longer attention span than popular myth suggests — the 9-second thing is completely made up.",
  "Nintendo was founded in 1889 — originally as a playing card company.",
  "The dot over the letters i and j has an official name: a tittle.",
  "Strawberries are not actually berries. Bananas technically are.",
  "Mosquitoes are the deadliest animals on Earth — not sharks, not lions.",
  "Your left and right lungs are different sizes to make room for your heart.",
  "There are more stars in the universe than grains of sand on all of Earth's beaches.",
  "A blind chameleon still changes colour to match its surroundings.",
  "The brain keeps developing until you are around 25 years old.",
  "Elephants are the only animals that cannot jump. They also never forget. Coincidence?",
  "The human nose can detect over one trillion different scents.",
  "A bolt of lightning is five times hotter than the surface of the Sun.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "The average cloud weighs around 500,000 kilograms.",
  "Sloths can hold their breath longer than dolphins — up to 40 minutes.",
  "Your brain produces enough electricity to power a smartphone — just barely.",
  "The first computer bug was an actual bug — a moth found in a Harvard computer in 1947.",
  "Rats laugh when tickled but at a frequency too high for humans to hear.",
  "A group of pandas is called an embarrassment.",
  "It takes more muscles to frown than to smile — but both are good workouts.",
  "The average brain makes about 70,000 thoughts per day.",
  "Crows remember human faces and can hold grudges for years.",
  "You cannot dream about a face you have never seen — every face in your dreams is someone you have encountered.",
]
